### ISSUE TITLE
Try alternative CI solution

### ISSUE THREAD

**Issue by Kauhsa** [TheSoftwareFactory/lokki-android#120]
Basically, I want to see if we can improve from using Travis by having our own CI server. My first idea is to use one of the computers of our Software Factory room as a CI server and see would it work at all – if it looks like it works better than Travis, maybe we can get an actual server from somewhere.

**Comment by Kauhsa** [comment]
I tinkered around with this today. I managed to have CI with builds taking around 2 minutes (quite an improvement from Travis!) that update the build status on pull requests just like Travis does. Only problem right now is that the CI server that I've been trying out (https://github.com/danielbeardsley/cimpler) doesn't support building pull requests that originate from other repositories. This is a deal breaker, but I might already have a fix for this, and trying it out shouldn't take too much time.

**Comment by Kauhsa** [comment]
Ok, got it to work (see https://github.com/Kauhsa/cimpler/commit/7c3f72ef712c5123ee82ebf93569a529dee9adee), but we might want to have a bit of discussion about it. Maybe when our attendance level is a bit higher :-)

**Comment by Kauhsa** [comment]
As a test, turned this on for the main repo. Now there are two different CI systems – Travis and the one running in Software Factory room.

**Comment by ffagerho** [comment]
Two questions:
1. Can the solution in https://github.com/Kauhsa/cimpler/commit/7c3f72ef712c5123ee82ebf93569a529dee9adee be deployed to "the cloud" in some way, meaning can it be deployed to something like Heroku so we would not need to run it locally?
2. Have you investigated the reasons for Travis' slowness? Is it even possible to improve the situation while still running Travis?

**Comment by Kauhsa** [comment]
Okay, so there are two different reasons why Travis is slow:

1. Launching the test environment from scratch every time. This is fine, if there's not a lot of overhead from installing all the required things to test environment. In case of Android development, there's plenty – installing the SDK takes a while, and even worse, launching the emulator takes a long time (especially when combined with point two). This is where the most our speedup is coming from, because if we're having our own CI server, we don't need to reset the environment every time. I guess there's a possibility that this aspect could be improved – maybe we can utilize caching solutions in Travis to avoid installing android SDK every time, launch emulator from a snapshot etc etc.
2. Emulator can't be run in x86 mode. This is impossible with Travis, since they don't have KVM available (and apparently can't have KVM – see https://github.com/travis-ci/travis-ci/issues/1419).

If it was only slowness, we could probably deal with this, but there's a lot of flakiness in Travis builds that a more performant CI solution seems to be able to avoid. This means we have to restart builds all the time to get one build that passes. I'm not 100% sure why it is this way – I'm think the emulator is running too slow in ARM mode, but that's just a guess.

So, ideally we would have our own server that supports KVM to fix both of these issues. Something like VPS would be fine, but I'm not sure how common KVM support in virtual servers is. Heroku most certainly doesn't have it.

**Comment by ffagerho** [comment]
I ran some tests using Travis, another hosted CI system, and an artificially loaded local system. The results were consistent: when the system is loaded, random errors start occurring regardless of what software is driving the builds. I traced this down to two separate things:

1. The adb install timeout. When the emulator doesn't respond quickly enough to adb's apk install request, the build fails. This can be fixed by increasing the timeout significantly.
2. UI animations. With animations on (which is the emulator default), espresso sometimes gets confused. Presumably, this gets worse under load when animations are slower. This can be fixed by turning animations off programmatically, which is possible but needs some work. Here's a nice link with info on that: https://code.google.com/p/android-test-kit/wiki/DisablingAnimations

My current hypothesis is that we don't need to switch CI just yet, just fix the two above issues and perhaps tweak the emulator settings a bit. That should give us more stability. Later, if we need more speed, we can consider other CI options.

**Comment by Kauhsa** [comment]
Okay, so the status is that people are probably still partly relying to the CI hack I built. Since it's just running on my account, and the process of setting it up is totally undocumented, I think we need to decide something here – is it something we want to keep up or not? I think @josalmi tried (still tries?) to look at improving Travis stability, but I'm not sure if he lost his sanity in progress.

BTW, you're correct on 1. and 2. – these are something that are fixed on my CI hack as well, which is also a part of the reason why it works so well compared to Travis. You note that the real culprit is system load – this is probably true, but I think there's load in the first place because ARM emulation generates a whole lot of it compared to virtualization.
