### ISSUE TITLE
User can log out of the app

### ISSUE THREAD

**Issue by ffagerho** [TheSoftwareFactory/lokki-android#287]
The app should have a "Log out" feature that resets the app to its initial state and allows the user to log in again.

**Comment by DocV** [comment]
Partially addressed in https://github.com/TheSoftwareFactory/lokki-android/pull/290
The app has a working logout button now, but we need to store some data on the server instead of the app so that it doesn't get shared between users.
See: https://github.com/TheSoftwareFactory/lokki-android/issues/291

**Comment by DocV** [comment]
Contacts no longer seem, to be shared  between users as of #317 , so I'm closing this
